version: '2'

services:
  neo4j:
    image: neo4j:3.3.5
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - $HOME/neo4j/data:/data
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node